import 'package:json_annotation/json_annotation.dart';
import 'state.dart';
import 'media.dart';
part 'chapter.g.dart';

@JsonSerializable(anyMap: true, checked: true, fieldRename: FieldRename.snake)
class SubChapter {
  List<Media> media;

  SubChapter(this.media);

  /// Factory function for creating from json, generated by json_serializable
  factory SubChapter.fromJson(Map json) => _$SubChapterFromJson(json);
}

@JsonSerializable(anyMap: true, fieldRename: FieldRename.snake)
class Chapter {
  String id;
  String? name;
  State state;
  List<SubChapter> subs;

  Chapter(this.id, this.subs, {this.name, var state})
    : this.state = fromMap(state);

  /// Factory function for creating from json, generated by json_serializable
  factory Chapter.fromJson(Map json) => _$ChapterFromJson(json);
}
