import 'package:json_annotation/json_annotation.dart';
import 'media.dart';
part 'media.g.dart';

enum MediaType {
  text,
  audio,
  image,
  conditional,
}

class Media {
  final MediaType type;

  Media(this.type);

  /// Factory function for creating from json, generated by json_serializable
  factory Media.fromJson(Map json) {
    if (json.containsKey('audio'))
      return Audio.fromJson(json['audio']);
    throw Exception('Unknown media type');
  }

  Map<String, dynamic> toJson() => {};
}

@JsonSerializable(anyMap: true, checked: true, fieldRename: FieldRename.snake)
class Audio extends Media {
  String src;

  Audio(this.src)
    : super(MediaType.audio);

  /// Factory function for creating from json, generated by json_serializable
  factory Audio.fromJson(Map json) => _$AudioFromJson(json);
}
