import 'package:json_annotation/json_annotation.dart';
import 'state.dart';
import 'chapter.dart';
import 'player_path.dart';
part 'novel.g.dart';

@JsonSerializable(anyMap: true, fieldRename: FieldRename.snake)
class Novel {
  String? name;
  State state;
  List<Chapter> chapters;
  List<PlayerPath> players;

  Novel(this.chapters, this.players, {this.name, var state})
    : this.state = fromMap(state);

  /// Factory function for creating from json, generated by json_serializable
  factory Novel.fromJson(Map json) => _$NovelFromJson(json);
}
